### ISSUE TITLE
edit data download

### ISSUE THREAD

**Issue by jmithani** [fivethirtyeight/covid-19-polls#3]
- Should we separate data downloads by admin?
- Is there anything else we need to include in the downloads?

**Comment by jmithani** [comment]
From my understanding, since the download just pulls from https://github.com/fivethirtyeight/covid-19-polls/, once we update it with Biden data the downloads should automatically adjust to include them.

I don't see an open PR here and the data in this repo hasn't been updated in a few weeks. @bycoffe what do we need to do to get the Biden polls added this repo?

**Comment by bycoffe** [comment]
@dmil Set this up so he would know more, but my understanding from looking at [the code](https://github.com/fivethirtyeight/covid-19-poll-tracker/blob/master/tasks/upload.rb) is that it takes the data from the [covid-19-poll-tracker](https://github.com/fivethirtyeight/covid-19-poll-tracker) repo, formats it and commits it to [this repo](https://github.com/fivethirtyeight/covid-19-polls). It's possible that all we'll need to do is add `Biden` to [this line](https://github.com/fivethirtyeight/covid-19-poll-tracker/blob/master/tasks/upload.rb#L30). I think we can wait until after the new version is published to make that change, since I don't see an easy way to test it.

**Comment by jmithani** [comment]
Ah, got it. Thank you Aaron!

**Comment by dmil** [comment]
Yup, just need to update these three lines:

- https://github.com/fivethirtyeight/covid-19-poll-tracker/blob/master/tasks/upload.rb#L30
- https://github.com/fivethirtyeight/covid-19-poll-tracker/blob/master/tasks/upload.rb#L50
- https://github.com/fivethirtyeight/covid-19-poll-tracker/blob/master/tasks/upload.rb#L70

And then update the README here:

https://github.com/fivethirtyeight/covid-19-polls

**Comment by bycoffe** [comment]
Changed in fivethirtyeight/covid-19-poll-tracker@e64b78a600ac0932a911905a677fb004d0fe8bf0
